/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesCaseIdIndexRouteImport } from './routes/cases.$caseId.index'
import { Route as CasesCaseIdGraphRouteImport } from './routes/cases.$caseId.graph'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdIndexRoute = CasesCaseIdIndexRouteImport.update({
  id: '/cases/$caseId/',
  path: '/cases/$caseId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdGraphRoute = CasesCaseIdGraphRouteImport.update({
  id: '/cases/$caseId/graph',
  path: '/cases/$caseId/graph',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases/$caseId/graph': typeof CasesCaseIdGraphRoute
  '/cases/$caseId/': typeof CasesCaseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases/$caseId/graph': typeof CasesCaseIdGraphRoute
  '/cases/$caseId': typeof CasesCaseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases/$caseId/graph': typeof CasesCaseIdGraphRoute
  '/cases/$caseId/': typeof CasesCaseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cases/$caseId/graph' | '/cases/$caseId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cases/$caseId/graph' | '/cases/$caseId'
  id: '__root__' | '/' | '/cases/$caseId/graph' | '/cases/$caseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesCaseIdGraphRoute: typeof CasesCaseIdGraphRoute
  CasesCaseIdIndexRoute: typeof CasesCaseIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId/': {
      id: '/cases/$caseId/'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId/'
      preLoaderRoute: typeof CasesCaseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId/graph': {
      id: '/cases/$caseId/graph'
      path: '/cases/$caseId/graph'
      fullPath: '/cases/$caseId/graph'
      preLoaderRoute: typeof CasesCaseIdGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesCaseIdGraphRoute: CasesCaseIdGraphRoute,
  CasesCaseIdIndexRoute: CasesCaseIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
